spring:
  application:
    name: springcloud-client-provider

server:
  port: 8011

eureka:
  client:
    service-url:
      defaultZone: http://eureka-01:8001/eureka/,http://eureka-02:8002/eureka/,http://eureka-03:8003/eureka/